name: watermaniac
description: A new Flutter project.

version: 1.0.5+21

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  redux: ^5.0.0
  cupertino_icons: ^1.0.5
  shared_preferences: ^2.2.0
  intl: ^0.18.1
  flutter_svg: ^2.0.7
  flutter_local_notifications: ^15.1.0+1
  firebase_admob: ^0.11.2
  flutter_redux: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/buttons/
    - assets/icons/
    - assets/background/
